//
// Generated file, do not edit! Created by nedtool 5.4 from messages/PrimaryBackupUpdate.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PRIMARYBACKUPUPDATE_M_H
#define __PRIMARYBACKUPUPDATE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "Update_m.h"
// }}

/**
 * Class generated from <tt>messages/PrimaryBackupUpdate.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet PrimaryBackupUpdate extends Update
 * {
 *     int stateIndex;
 *     unsigned long state;
 * }
 * </pre>
 */
class PrimaryBackupUpdate : public ::Update
{
  protected:
    int stateIndex;
    unsigned long state;

  private:
    void copy(const PrimaryBackupUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PrimaryBackupUpdate&);

  public:
    PrimaryBackupUpdate(const char *name=nullptr, short kind=0);
    PrimaryBackupUpdate(const PrimaryBackupUpdate& other);
    virtual ~PrimaryBackupUpdate();
    PrimaryBackupUpdate& operator=(const PrimaryBackupUpdate& other);
    virtual PrimaryBackupUpdate *dup() const override {return new PrimaryBackupUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getStateIndex() const;
    virtual void setStateIndex(int stateIndex);
    virtual unsigned long getState() const;
    virtual void setState(unsigned long state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PrimaryBackupUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PrimaryBackupUpdate& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PRIMARYBACKUPUPDATE_M_H

