//
// Generated file, do not edit! Created by nedtool 5.4 from messages/StateApply.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __STATEAPPLY_M_H
#define __STATEAPPLY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/StateApply.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet StateApply
 * {
 *     int stateIndex;
 *     unsigned long state;
 * }
 * </pre>
 */
class StateApply : public ::omnetpp::cPacket
{
  protected:
    int stateIndex;
    unsigned long state;

  private:
    void copy(const StateApply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StateApply&);

  public:
    StateApply(const char *name=nullptr, short kind=0);
    StateApply(const StateApply& other);
    virtual ~StateApply();
    StateApply& operator=(const StateApply& other);
    virtual StateApply *dup() const override {return new StateApply(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getStateIndex() const;
    virtual void setStateIndex(int stateIndex);
    virtual unsigned long getState() const;
    virtual void setState(unsigned long state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StateApply& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StateApply& obj) {obj.parsimUnpack(b);}


#endif // ifndef __STATEAPPLY_M_H

