//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/GRQueryReply.msg.
//

#ifndef _GRQUERYREPLY_M_H_
#define _GRQUERYREPLY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>messages/GRQueryReply.msg</tt> by opp_msgc.
 * <pre>
 * packet GRQueryReply {
 *     string displayString = DISPLAY_STR_MSG_GROUP_GR;
 *     
 *     string senderName;
 *     int epoch;
 *     int groupId;
 *     string groupMembers;
 *     string state;
 *     int escId;
 *     long esc;
 * }
 * </pre>
 */
class GRQueryReply : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string senderName_var;
    int epoch_var;
    int groupId_var;
    opp_string groupMembers_var;
    opp_string state_var;
    int escId_var;
    long esc_var;

  private:
    void copy(const GRQueryReply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GRQueryReply&);

  public:
    GRQueryReply(const char *name=NULL, int kind=0);
    GRQueryReply(const GRQueryReply& other);
    virtual ~GRQueryReply();
    GRQueryReply& operator=(const GRQueryReply& other);
    virtual GRQueryReply *dup() const {return new GRQueryReply(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual const char * getGroupMembers() const;
    virtual void setGroupMembers(const char * groupMembers);
    virtual const char * getState() const;
    virtual void setState(const char * state);
    virtual int getEscId() const;
    virtual void setEscId(int escId);
    virtual long getEsc() const;
    virtual void setEsc(long esc);
};

inline void doPacking(cCommBuffer *b, GRQueryReply& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GRQueryReply& obj) {obj.parsimUnpack(b);}


#endif // _GRQUERYREPLY_M_H_
