//
// Generated file, do not edit! Created by opp_msgc 4.2 from basicSMR/messages/HBResponse.msg.
//

#ifndef _HBRESPONSE_M_H_
#define _HBRESPONSE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>basicSMR/messages/HBResponse.msg</tt> by opp_msgc.
 * <pre>
 * packet HBResponse {
 *     string displayString = DISPLAY_STR_MSG_HIDDEN;
 *     
 *     string sourceName;
 *     string destName;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class HBResponse : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string sourceName_var;
    opp_string destName_var;
    simtime_t timestamp_var;

  private:
    void copy(const HBResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HBResponse&);

  public:
    HBResponse(const char *name=NULL, int kind=0);
    HBResponse(const HBResponse& other);
    virtual ~HBResponse();
    HBResponse& operator=(const HBResponse& other);
    virtual HBResponse *dup() const {return new HBResponse(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
    virtual simtime_t getTimestamp() const;
    virtual void setTimestamp(simtime_t timestamp);
};

inline void doPacking(cCommBuffer *b, HBResponse& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HBResponse& obj) {obj.parsimUnpack(b);}


#endif // _HBRESPONSE_M_H_
