//
// Generated file, do not edit! Created by opp_msgc 4.2 from unreliable/messages/ReconfigResp.msg.
//

#ifndef _RECONFIGRESP_M_H_
#define _RECONFIGRESP_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>unreliable/messages/ReconfigResp.msg</tt> by opp_msgc.
 * <pre>
 * packet ReconfigResp {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 *     
 *     string senderName;
 * }
 * </pre>
 */
class ReconfigResp : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string senderName_var;

  private:
    void copy(const ReconfigResp& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReconfigResp&);

  public:
    ReconfigResp(const char *name=NULL, int kind=0);
    ReconfigResp(const ReconfigResp& other);
    virtual ~ReconfigResp();
    ReconfigResp& operator=(const ReconfigResp& other);
    virtual ReconfigResp *dup() const {return new ReconfigResp(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
};

inline void doPacking(cCommBuffer *b, ReconfigResp& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ReconfigResp& obj) {obj.parsimUnpack(b);}


#endif // _RECONFIGRESP_M_H_
