//
// Generated file, do not edit! Created by opp_msgc 4.2 from unreliable/messages/Update.msg.
//

#ifndef _UPDATE_M_H_
#define _UPDATE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>unreliable/messages/Update.msg</tt> by opp_msgc.
 * <pre>
 * packet Update {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 *     
 *     unsigned long senderId;
 *     int seq;
 *     string content;
 *     
 *     
 *     string sourceName;
 *     string destName;
 * }
 * </pre>
 */
class Update : public ::cPacket
{
  protected:
    opp_string displayString_var;
    unsigned long senderId_var;
    int seq_var;
    opp_string content_var;
    opp_string sourceName_var;
    opp_string destName_var;

  private:
    void copy(const Update& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Update&);

  public:
    Update(const char *name=NULL, int kind=0);
    Update(const Update& other);
    virtual ~Update();
    Update& operator=(const Update& other);
    virtual Update *dup() const {return new Update(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual unsigned long getSenderId() const;
    virtual void setSenderId(unsigned long senderId);
    virtual int getSeq() const;
    virtual void setSeq(int seq);
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
};

inline void doPacking(cCommBuffer *b, Update& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Update& obj) {obj.parsimUnpack(b);}


#endif // _UPDATE_M_H_
