//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/Gossip.msg.
//

#ifndef _GOSSIP_M_H_
#define _GOSSIP_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>messages/Gossip.msg</tt> by opp_msgc.
 * <pre>
 * packet Gossip {
 *     string sourceName;
 *     string destName;  
 *     simtime_t sendTime;
 *     int lastRound;
 * }
 * </pre>
 */
class Gossip : public ::cPacket
{
  protected:
    opp_string sourceName_var;
    opp_string destName_var;
    simtime_t sendTime_var;
    int lastRound_var;

  private:
    void copy(const Gossip& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Gossip&);

  public:
    Gossip(const char *name=NULL, int kind=0);
    Gossip(const Gossip& other);
    virtual ~Gossip();
    Gossip& operator=(const Gossip& other);
    virtual Gossip *dup() const {return new Gossip(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
    virtual int getLastRound() const;
    virtual void setLastRound(int lastRound);
};

inline void doPacking(cCommBuffer *b, Gossip& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Gossip& obj) {obj.parsimUnpack(b);}


#endif // _GOSSIP_M_H_
