//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/RoundQueryReply.msg.
//

#ifndef _ROUNDQUERYREPLY_M_H_
#define _ROUNDQUERYREPLY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>messages/RoundQueryReply.msg</tt> by opp_msgc.
 * <pre>
 * packet RoundQueryReply {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 *     
 *     string senderName;
 *     string destName;
 *     int round;
 *     string events;
 * }
 * </pre>
 */
class RoundQueryReply : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string senderName_var;
    opp_string destName_var;
    int round_var;
    opp_string events_var;

  private:
    void copy(const RoundQueryReply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RoundQueryReply&);

  public:
    RoundQueryReply(const char *name=NULL, int kind=0);
    RoundQueryReply(const RoundQueryReply& other);
    virtual ~RoundQueryReply();
    RoundQueryReply& operator=(const RoundQueryReply& other);
    virtual RoundQueryReply *dup() const {return new RoundQueryReply(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual const char * getEvents() const;
    virtual void setEvents(const char * events);
};

inline void doPacking(cCommBuffer *b, RoundQueryReply& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RoundQueryReply& obj) {obj.parsimUnpack(b);}


#endif // _ROUNDQUERYREPLY_M_H_
