//
// Generated file, do not edit! Created by opp_msgc 4.2 from fastSMR/messages/CCQuery.msg.
//

#ifndef _CCQUERY_M_H_
#define _CCQUERY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>fastSMR/messages/CCQuery.msg</tt> by opp_msgc.
 * <pre>
 * packet CCQuery {
 * 	string displayString = DISPLAY_STR_MSG_GROUP_CC;
 *     
 *     string candidateName;
 * }
 * </pre>
 */
class CCQuery : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string candidateName_var;

  private:
    void copy(const CCQuery& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CCQuery&);

  public:
    CCQuery(const char *name=NULL, int kind=0);
    CCQuery(const CCQuery& other);
    virtual ~CCQuery();
    CCQuery& operator=(const CCQuery& other);
    virtual CCQuery *dup() const {return new CCQuery(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getCandidateName() const;
    virtual void setCandidateName(const char * candidateName);
};

inline void doPacking(cCommBuffer *b, CCQuery& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CCQuery& obj) {obj.parsimUnpack(b);}


#endif // _CCQUERY_M_H_
