//
// Generated file, do not edit! Created by opp_msgc 4.2 from fastSMR/messages/InitJoin.msg.
//

#ifndef _INITJOIN_M_H_
#define _INITJOIN_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>fastSMR/messages/InitJoin.msg</tt> by opp_msgc.
 * <pre>
 * packet InitJoin {
 *     unsigned long senderId;
 *     int seq;
 *     string sourceName;
 *     string destName;
 *     simtime_t joinTime;
 * }
 * </pre>
 */
class InitJoin : public ::cPacket
{
  protected:
    unsigned long senderId_var;
    int seq_var;
    opp_string sourceName_var;
    opp_string destName_var;
    simtime_t joinTime_var;

  private:
    void copy(const InitJoin& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InitJoin&);

  public:
    InitJoin(const char *name=NULL, int kind=0);
    InitJoin(const InitJoin& other);
    virtual ~InitJoin();
    InitJoin& operator=(const InitJoin& other);
    virtual InitJoin *dup() const {return new InitJoin(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getSenderId() const;
    virtual void setSenderId(unsigned long senderId);
    virtual int getSeq() const;
    virtual void setSeq(int seq);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
    virtual simtime_t getJoinTime() const;
    virtual void setJoinTime(simtime_t joinTime);
};

inline void doPacking(cCommBuffer *b, InitJoin& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, InitJoin& obj) {obj.parsimUnpack(b);}


#endif // _INITJOIN_M_H_
