//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/ConsensusQuery.msg.
//

#ifndef _CONSENSUSQUERY_M_H_
#define _CONSENSUSQUERY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>messages/ConsensusQuery.msg</tt> by opp_msgc.
 * <pre>
 * packet ConsensusQuery {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 *     
 *     string senderName;
 *     int epoch;
 *     int groupId;
 *     int round;
 *     string seqRanges;
 * }
 * </pre>
 */
class ConsensusQuery : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string senderName_var;
    int epoch_var;
    int groupId_var;
    int round_var;
    opp_string seqRanges_var;

  private:
    void copy(const ConsensusQuery& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConsensusQuery&);

  public:
    ConsensusQuery(const char *name=NULL, int kind=0);
    ConsensusQuery(const ConsensusQuery& other);
    virtual ~ConsensusQuery();
    ConsensusQuery& operator=(const ConsensusQuery& other);
    virtual ConsensusQuery *dup() const {return new ConsensusQuery(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual const char * getSeqRanges() const;
    virtual void setSeqRanges(const char * seqRanges);
};

inline void doPacking(cCommBuffer *b, ConsensusQuery& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ConsensusQuery& obj) {obj.parsimUnpack(b);}


#endif // _CONSENSUSQUERY_M_H_
