//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/Decision.msg.
//

#ifndef _DECISION_M_H_
#define _DECISION_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>messages/Decision.msg</tt> by opp_msgc.
 * <pre>
 * packet Decision {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 *     
 *     string senderName;
 *     int round;
 *     int epoch;
 *     int groupId;
 *     string decision;
 * }
 * </pre>
 */
class Decision : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string senderName_var;
    int round_var;
    int epoch_var;
    int groupId_var;
    opp_string decision_var;

  private:
    void copy(const Decision& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Decision&);

  public:
    Decision(const char *name=NULL, int kind=0);
    Decision(const Decision& other);
    virtual ~Decision();
    Decision& operator=(const Decision& other);
    virtual Decision *dup() const {return new Decision(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual const char * getDecision() const;
    virtual void setDecision(const char * decision);
};

inline void doPacking(cCommBuffer *b, Decision& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Decision& obj) {obj.parsimUnpack(b);}


#endif // _DECISION_M_H_
