//
// Generated file, do not edit! Created by opp_msgc 4.2 from fastSMR/messages/CycleEvent.msg.
//

#ifndef _CYCLEEVENT_M_H_
#define _CYCLEEVENT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>fastSMR/messages/CycleEvent.msg</tt> by opp_msgc.
 * <pre>
 * packet CycleEvent {
 *     string displayString = DISPLAY_STR_MSG_GROUP_CC;
 *     
 *     string senderName;
 *     int round;
 *     string cycleEvents;
 * }
 * </pre>
 */
class CycleEvent : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string senderName_var;
    int round_var;
    opp_string cycleEvents_var;

  private:
    void copy(const CycleEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CycleEvent&);

  public:
    CycleEvent(const char *name=NULL, int kind=0);
    CycleEvent(const CycleEvent& other);
    virtual ~CycleEvent();
    CycleEvent& operator=(const CycleEvent& other);
    virtual CycleEvent *dup() const {return new CycleEvent(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual const char * getCycleEvents() const;
    virtual void setCycleEvents(const char * cycleEvents);
};

inline void doPacking(cCommBuffer *b, CycleEvent& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CycleEvent& obj) {obj.parsimUnpack(b);}


#endif // _CYCLEEVENT_M_H_
