//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/Event.msg.
//

#ifndef _EVENT_M_H_
#define _EVENT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/Event.msg</tt> by opp_msgc.
 * <pre>
 * packet Event {
 *     unsigned long senderId;
 *     int seq;
 *     string content;
 *     
 *     
 *     string sourceName;
 *     string destName;
 * }
 * </pre>
 */
class Event : public ::cPacket
{
  protected:
    unsigned long senderId_var;
    int seq_var;
    opp_string content_var;
    opp_string sourceName_var;
    opp_string destName_var;

  private:
    void copy(const Event& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Event&);

  public:
    Event(const char *name=NULL, int kind=0);
    Event(const Event& other);
    virtual ~Event();
    Event& operator=(const Event& other);
    virtual Event *dup() const {return new Event(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getSenderId() const;
    virtual void setSenderId(unsigned long senderId);
    virtual int getSeq() const;
    virtual void setSeq(int seq);
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
};

inline void doPacking(cCommBuffer *b, Event& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Event& obj) {obj.parsimUnpack(b);}


#endif // _EVENT_M_H_
