//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/Failure.msg.
//

#ifndef _FAILURE_M_H_
#define _FAILURE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/Failure.msg</tt> by opp_msgc.
 * <pre>
 * packet Failure {
 *     string hostAddress;
 * }
 * </pre>
 */
class Failure : public ::cPacket
{
  protected:
    opp_string hostAddress_var;

  private:
    void copy(const Failure& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Failure&);

  public:
    Failure(const char *name=NULL, int kind=0);
    Failure(const Failure& other);
    virtual ~Failure();
    Failure& operator=(const Failure& other);
    virtual Failure *dup() const {return new Failure(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getHostAddress() const;
    virtual void setHostAddress(const char * hostAddress);
};

inline void doPacking(cCommBuffer *b, Failure& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Failure& obj) {obj.parsimUnpack(b);}


#endif // _FAILURE_M_H_
