//
// Generated file, do not edit! Created by opp_msgc 4.2 from basicSMR/messages/BSMRAgree.msg.
//

#ifndef _BSMRAGREE_M_H_
#define _BSMRAGREE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>basicSMR/messages/BSMRAgree.msg</tt> by opp_msgc.
 * <pre>
 * packet BSMRAgree {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 *     
 *     string senderName;
 *     int epoch;
 *     int groupId;
 * }
 * </pre>
 */
class BSMRAgree : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string senderName_var;
    int epoch_var;
    int groupId_var;

  private:
    void copy(const BSMRAgree& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BSMRAgree&);

  public:
    BSMRAgree(const char *name=NULL, int kind=0);
    BSMRAgree(const BSMRAgree& other);
    virtual ~BSMRAgree();
    BSMRAgree& operator=(const BSMRAgree& other);
    virtual BSMRAgree *dup() const {return new BSMRAgree(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
};

inline void doPacking(cCommBuffer *b, BSMRAgree& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BSMRAgree& obj) {obj.parsimUnpack(b);}


#endif // _BSMRAGREE_M_H_
