//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/ConnectReply.msg.
//

#ifndef _CONNECTREPLY_M_H_
#define _CONNECTREPLY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/ConnectReply.msg</tt> by opp_msgc.
 * <pre>
 * packet ConnectReply {
 *     string hostAddrs;
 * }
 * </pre>
 */
class ConnectReply : public ::cPacket
{
  protected:
    opp_string hostAddrs_var;

  private:
    void copy(const ConnectReply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectReply&);

  public:
    ConnectReply(const char *name=NULL, int kind=0);
    ConnectReply(const ConnectReply& other);
    virtual ~ConnectReply();
    ConnectReply& operator=(const ConnectReply& other);
    virtual ConnectReply *dup() const {return new ConnectReply(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getHostAddrs() const;
    virtual void setHostAddrs(const char * hostAddrs);
};

inline void doPacking(cCommBuffer *b, ConnectReply& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ConnectReply& obj) {obj.parsimUnpack(b);}


#endif // _CONNECTREPLY_M_H_
