//
// Generated file, do not edit! Created by opp_msgc 4.2 from unreliable/messages/CoordResponse.msg.
//

#ifndef _COORDRESPONSE_M_H_
#define _COORDRESPONSE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>unreliable/messages/CoordResponse.msg</tt> by opp_msgc.
 * <pre>
 * packet CoordResponse {
 *     string coordFullName;
 * }
 * </pre>
 */
class CoordResponse : public ::cPacket
{
  protected:
    opp_string coordFullName_var;

  private:
    void copy(const CoordResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CoordResponse&);

  public:
    CoordResponse(const char *name=NULL, int kind=0);
    CoordResponse(const CoordResponse& other);
    virtual ~CoordResponse();
    CoordResponse& operator=(const CoordResponse& other);
    virtual CoordResponse *dup() const {return new CoordResponse(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getCoordFullName() const;
    virtual void setCoordFullName(const char * coordFullName);
};

inline void doPacking(cCommBuffer *b, CoordResponse& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CoordResponse& obj) {obj.parsimUnpack(b);}


#endif // _COORDRESPONSE_M_H_
