//
// Generated file, do not edit! Created by opp_msgc 4.2 from unreliable/messages/Heartbeat.msg.
//

#ifndef _HEARTBEAT_M_H_
#define _HEARTBEAT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>unreliable/messages/Heartbeat.msg</tt> by opp_msgc.
 * <pre>
 * packet Heartbeat {
 *     string displayString = DISPLAY_STR_MSG_HIDDEN;
 *     
 *     string sourceName;
 *     string destName;
 *     string survivals;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class Heartbeat : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string sourceName_var;
    opp_string destName_var;
    opp_string survivals_var;
    simtime_t timestamp_var;

  private:
    void copy(const Heartbeat& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Heartbeat&);

  public:
    Heartbeat(const char *name=NULL, int kind=0);
    Heartbeat(const Heartbeat& other);
    virtual ~Heartbeat();
    Heartbeat& operator=(const Heartbeat& other);
    virtual Heartbeat *dup() const {return new Heartbeat(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
    virtual const char * getSurvivals() const;
    virtual void setSurvivals(const char * survivals);
    virtual simtime_t getTimestamp() const;
    virtual void setTimestamp(simtime_t timestamp);
};

inline void doPacking(cCommBuffer *b, Heartbeat& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Heartbeat& obj) {obj.parsimUnpack(b);}


#endif // _HEARTBEAT_M_H_
