//
// Generated file, do not edit! Created by opp_msgc 4.2 from unreliable/messages/Reconfig.msg.
//

#ifndef _RECONFIG_M_H_
#define _RECONFIG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Constants.h"
// }}



/**
 * Class generated from <tt>unreliable/messages/Reconfig.msg</tt> by opp_msgc.
 * <pre>
 * packet Reconfig {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 *     
 *     string members;
 * }
 * </pre>
 */
class Reconfig : public ::cPacket
{
  protected:
    opp_string displayString_var;
    opp_string members_var;

  private:
    void copy(const Reconfig& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Reconfig&);

  public:
    Reconfig(const char *name=NULL, int kind=0);
    Reconfig(const Reconfig& other);
    virtual ~Reconfig();
    Reconfig& operator=(const Reconfig& other);
    virtual Reconfig *dup() const {return new Reconfig(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getMembers() const;
    virtual void setMembers(const char * members);
};

inline void doPacking(cCommBuffer *b, Reconfig& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Reconfig& obj) {obj.parsimUnpack(b);}


#endif // _RECONFIG_M_H_
